/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.launcher.syntax3.node;

import org.sablecc.sablecc.launcher.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TLongName extends Token
{
    public TLongName(String text)
    {
        setText(text);
    }

    public TLongName(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLongName(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLongName(this);
    }
}
