/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.c.macro;

public class MInclude {

    private final String pName;

    private final MInclude mInclude = this;

    MInclude(
            String pName) {

        if (pName == null) {
            throw new NullPointerException();
        }
        this.pName = pName;
    }

    String pName() {

        return this.pName;
    }

    private String rName() {

        return this.mInclude.pName();
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("#include \"M");
        sb.append(rName());
        sb.append(".h\"");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
