/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.objectmacro.launcher.syntax3.node;

import org.sablecc.objectmacro.launcher.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AShortOption extends PShortOption
{
    private TShortName _shortName_;
    private POperand _operand_;

    public AShortOption()
    {
        // Constructor
    }

    public AShortOption(
        @SuppressWarnings("hiding") TShortName _shortName_,
        @SuppressWarnings("hiding") POperand _operand_)
    {
        // Constructor
        setShortName(_shortName_);

        setOperand(_operand_);

    }

    @Override
    public Object clone()
    {
        return new AShortOption(
            cloneNode(this._shortName_),
            cloneNode(this._operand_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAShortOption(this);
    }

    public TShortName getShortName()
    {
        return this._shortName_;
    }

    public void setShortName(TShortName node)
    {
        if(this._shortName_ != null)
        {
            this._shortName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._shortName_ = node;
    }

    public POperand getOperand()
    {
        return this._operand_;
    }

    public void setOperand(POperand node)
    {
        if(this._operand_ != null)
        {
            this._operand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operand_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._shortName_)
            + toString(this._operand_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._shortName_ == child)
        {
            this._shortName_ = null;
            return;
        }

        if(this._operand_ == child)
        {
            this._operand_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._shortName_ == oldChild)
        {
            setShortName((TShortName) newChild);
            return;
        }

        if(this._operand_ == oldChild)
        {
            setOperand((POperand) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
