/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import java.util.*;
import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AGroup extends PGroup
{
    private TGroupKeyword _groupKeyword_;
    private TIdentifier _name_;
    private TColon _colon_;
    private final LinkedList<PUnit> _unit_ = new LinkedList<PUnit>();

    public AGroup()
    {
        // Constructor
    }

    public AGroup(
        @SuppressWarnings("hiding") TGroupKeyword _groupKeyword_,
        @SuppressWarnings("hiding") TIdentifier _name_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") List<PUnit> _unit_)
    {
        // Constructor
        setGroupKeyword(_groupKeyword_);

        setName(_name_);

        setColon(_colon_);

        setUnit(_unit_);

    }

    @Override
    public Object clone()
    {
        return new AGroup(
            cloneNode(this._groupKeyword_),
            cloneNode(this._name_),
            cloneNode(this._colon_),
            cloneList(this._unit_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGroup(this);
    }

    public TGroupKeyword getGroupKeyword()
    {
        return this._groupKeyword_;
    }

    public void setGroupKeyword(TGroupKeyword node)
    {
        if(this._groupKeyword_ != null)
        {
            this._groupKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._groupKeyword_ = node;
    }

    public TIdentifier getName()
    {
        return this._name_;
    }

    public void setName(TIdentifier node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public LinkedList<PUnit> getUnit()
    {
        return this._unit_;
    }

    public void setUnit(List<PUnit> list)
    {
        this._unit_.clear();
        this._unit_.addAll(list);
        for(PUnit e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._groupKeyword_)
            + toString(this._name_)
            + toString(this._colon_)
            + toString(this._unit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._groupKeyword_ == child)
        {
            this._groupKeyword_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._unit_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._groupKeyword_ == oldChild)
        {
            setGroupKeyword((TGroupKeyword) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((TIdentifier) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        for(ListIterator<PUnit> i = this._unit_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PUnit) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
