/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AIntervalExponentExpression extends PExpression
{
    private PExpression _expression_;
    private TCaret _caret_;
    private TNumber _from_;
    private TTwoDots _twoDots_;
    private TNumber _to_;

    public AIntervalExponentExpression()
    {
        // Constructor
    }

    public AIntervalExponentExpression(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TCaret _caret_,
        @SuppressWarnings("hiding") TNumber _from_,
        @SuppressWarnings("hiding") TTwoDots _twoDots_,
        @SuppressWarnings("hiding") TNumber _to_)
    {
        // Constructor
        setExpression(_expression_);

        setCaret(_caret_);

        setFrom(_from_);

        setTwoDots(_twoDots_);

        setTo(_to_);

    }

    @Override
    public Object clone()
    {
        return new AIntervalExponentExpression(
            cloneNode(this._expression_),
            cloneNode(this._caret_),
            cloneNode(this._from_),
            cloneNode(this._twoDots_),
            cloneNode(this._to_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntervalExponentExpression(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TCaret getCaret()
    {
        return this._caret_;
    }

    public void setCaret(TCaret node)
    {
        if(this._caret_ != null)
        {
            this._caret_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caret_ = node;
    }

    public TNumber getFrom()
    {
        return this._from_;
    }

    public void setFrom(TNumber node)
    {
        if(this._from_ != null)
        {
            this._from_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._from_ = node;
    }

    public TTwoDots getTwoDots()
    {
        return this._twoDots_;
    }

    public void setTwoDots(TTwoDots node)
    {
        if(this._twoDots_ != null)
        {
            this._twoDots_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._twoDots_ = node;
    }

    public TNumber getTo()
    {
        return this._to_;
    }

    public void setTo(TNumber node)
    {
        if(this._to_ != null)
        {
            this._to_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._to_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._caret_)
            + toString(this._from_)
            + toString(this._twoDots_)
            + toString(this._to_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._caret_ == child)
        {
            this._caret_ = null;
            return;
        }

        if(this._from_ == child)
        {
            this._from_ = null;
            return;
        }

        if(this._twoDots_ == child)
        {
            this._twoDots_ = null;
            return;
        }

        if(this._to_ == child)
        {
            this._to_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._caret_ == oldChild)
        {
            setCaret((TCaret) newChild);
            return;
        }

        if(this._from_ == oldChild)
        {
            setFrom((TNumber) newChild);
            return;
        }

        if(this._twoDots_ == oldChild)
        {
            setTwoDots((TTwoDots) newChild);
            return;
        }

        if(this._to_ == oldChild)
        {
            setTo((TNumber) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
