/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import java.util.*;
import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class ALexerContext extends PLexerContext
{
    private TIdentifier _name_;
    private PTokens _tokens_;
    private PIgnored _ignored_;
    private final LinkedList<PLexerPriority> _lexerPriorities_ = new LinkedList<PLexerPriority>();

    public ALexerContext()
    {
        // Constructor
    }

    public ALexerContext(
        @SuppressWarnings("hiding") TIdentifier _name_,
        @SuppressWarnings("hiding") PTokens _tokens_,
        @SuppressWarnings("hiding") PIgnored _ignored_,
        @SuppressWarnings("hiding") List<PLexerPriority> _lexerPriorities_)
    {
        // Constructor
        setName(_name_);

        setTokens(_tokens_);

        setIgnored(_ignored_);

        setLexerPriorities(_lexerPriorities_);

    }

    @Override
    public Object clone()
    {
        return new ALexerContext(
            cloneNode(this._name_),
            cloneNode(this._tokens_),
            cloneNode(this._ignored_),
            cloneList(this._lexerPriorities_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALexerContext(this);
    }

    public TIdentifier getName()
    {
        return this._name_;
    }

    public void setName(TIdentifier node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public PTokens getTokens()
    {
        return this._tokens_;
    }

    public void setTokens(PTokens node)
    {
        if(this._tokens_ != null)
        {
            this._tokens_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tokens_ = node;
    }

    public PIgnored getIgnored()
    {
        return this._ignored_;
    }

    public void setIgnored(PIgnored node)
    {
        if(this._ignored_ != null)
        {
            this._ignored_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ignored_ = node;
    }

    public LinkedList<PLexerPriority> getLexerPriorities()
    {
        return this._lexerPriorities_;
    }

    public void setLexerPriorities(List<PLexerPriority> list)
    {
        this._lexerPriorities_.clear();
        this._lexerPriorities_.addAll(list);
        for(PLexerPriority e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._tokens_)
            + toString(this._ignored_)
            + toString(this._lexerPriorities_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._tokens_ == child)
        {
            this._tokens_ = null;
            return;
        }

        if(this._ignored_ == child)
        {
            this._ignored_ = null;
            return;
        }

        if(this._lexerPriorities_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TIdentifier) newChild);
            return;
        }

        if(this._tokens_ == oldChild)
        {
            setTokens((PTokens) newChild);
            return;
        }

        if(this._ignored_ == oldChild)
        {
            setIgnored((PIgnored) newChild);
            return;
        }

        for(ListIterator<PLexerPriority> i = this._lexerPriorities_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PLexerPriority) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
