/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AManyUnaryOperator extends PUnaryOperator
{
    private PManyOperator _manyOperator_;

    public AManyUnaryOperator()
    {
        // Constructor
    }

    public AManyUnaryOperator(
        @SuppressWarnings("hiding") PManyOperator _manyOperator_)
    {
        // Constructor
        setManyOperator(_manyOperator_);

    }

    @Override
    public Object clone()
    {
        return new AManyUnaryOperator(
            cloneNode(this._manyOperator_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManyUnaryOperator(this);
    }

    public PManyOperator getManyOperator()
    {
        return this._manyOperator_;
    }

    public void setManyOperator(PManyOperator node)
    {
        if(this._manyOperator_ != null)
        {
            this._manyOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._manyOperator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._manyOperator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._manyOperator_ == child)
        {
            this._manyOperator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._manyOperator_ == oldChild)
        {
            setManyOperator((PManyOperator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
