/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import java.util.*;
import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AParserAlternative extends PParserAlternative
{
    private TAlternativeName _alternativeName_;
    private final LinkedList<PElement> _elements_ = new LinkedList<PElement>();
    private PDanglingElement _danglingElement_;

    public AParserAlternative()
    {
        // Constructor
    }

    public AParserAlternative(
        @SuppressWarnings("hiding") TAlternativeName _alternativeName_,
        @SuppressWarnings("hiding") List<PElement> _elements_,
        @SuppressWarnings("hiding") PDanglingElement _danglingElement_)
    {
        // Constructor
        setAlternativeName(_alternativeName_);

        setElements(_elements_);

        setDanglingElement(_danglingElement_);

    }

    @Override
    public Object clone()
    {
        return new AParserAlternative(
            cloneNode(this._alternativeName_),
            cloneList(this._elements_),
            cloneNode(this._danglingElement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParserAlternative(this);
    }

    public TAlternativeName getAlternativeName()
    {
        return this._alternativeName_;
    }

    public void setAlternativeName(TAlternativeName node)
    {
        if(this._alternativeName_ != null)
        {
            this._alternativeName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alternativeName_ = node;
    }

    public LinkedList<PElement> getElements()
    {
        return this._elements_;
    }

    public void setElements(List<PElement> list)
    {
        this._elements_.clear();
        this._elements_.addAll(list);
        for(PElement e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public PDanglingElement getDanglingElement()
    {
        return this._danglingElement_;
    }

    public void setDanglingElement(PDanglingElement node)
    {
        if(this._danglingElement_ != null)
        {
            this._danglingElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._danglingElement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._alternativeName_)
            + toString(this._elements_)
            + toString(this._danglingElement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._alternativeName_ == child)
        {
            this._alternativeName_ = null;
            return;
        }

        if(this._elements_.remove(child))
        {
            return;
        }

        if(this._danglingElement_ == child)
        {
            this._danglingElement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._alternativeName_ == oldChild)
        {
            setAlternativeName((TAlternativeName) newChild);
            return;
        }

        for(ListIterator<PElement> i = this._elements_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PElement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._danglingElement_ == oldChild)
        {
            setDanglingElement((PDanglingElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
