/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import java.util.*;
import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class ATokens extends PTokens
{
    private TTokenKeyword _tokenKeyword_;
    private final LinkedList<PUnit> _unit_ = new LinkedList<PUnit>();

    public ATokens()
    {
        // Constructor
    }

    public ATokens(
        @SuppressWarnings("hiding") TTokenKeyword _tokenKeyword_,
        @SuppressWarnings("hiding") List<PUnit> _unit_)
    {
        // Constructor
        setTokenKeyword(_tokenKeyword_);

        setUnit(_unit_);

    }

    @Override
    public Object clone()
    {
        return new ATokens(
            cloneNode(this._tokenKeyword_),
            cloneList(this._unit_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATokens(this);
    }

    public TTokenKeyword getTokenKeyword()
    {
        return this._tokenKeyword_;
    }

    public void setTokenKeyword(TTokenKeyword node)
    {
        if(this._tokenKeyword_ != null)
        {
            this._tokenKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tokenKeyword_ = node;
    }

    public LinkedList<PUnit> getUnit()
    {
        return this._unit_;
    }

    public void setUnit(List<PUnit> list)
    {
        this._unit_.clear();
        this._unit_.addAll(list);
        for(PUnit e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tokenKeyword_)
            + toString(this._unit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tokenKeyword_ == child)
        {
            this._tokenKeyword_ = null;
            return;
        }

        if(this._unit_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tokenKeyword_ == oldChild)
        {
            setTokenKeyword((TTokenKeyword) newChild);
            return;
        }

        for(ListIterator<PUnit> i = this._unit_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PUnit) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
