/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class ATransformedElementReference extends PElementReference
{
    private TIdentifier _element_;
    private TDot _dot_;
    private TIdentifier _part_;

    public ATransformedElementReference()
    {
        // Constructor
    }

    public ATransformedElementReference(
        @SuppressWarnings("hiding") TIdentifier _element_,
        @SuppressWarnings("hiding") TDot _dot_,
        @SuppressWarnings("hiding") TIdentifier _part_)
    {
        // Constructor
        setElement(_element_);

        setDot(_dot_);

        setPart(_part_);

    }

    @Override
    public Object clone()
    {
        return new ATransformedElementReference(
            cloneNode(this._element_),
            cloneNode(this._dot_),
            cloneNode(this._part_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATransformedElementReference(this);
    }

    public TIdentifier getElement()
    {
        return this._element_;
    }

    public void setElement(TIdentifier node)
    {
        if(this._element_ != null)
        {
            this._element_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._element_ = node;
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    public TIdentifier getPart()
    {
        return this._part_;
    }

    public void setPart(TIdentifier node)
    {
        if(this._part_ != null)
        {
            this._part_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._part_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._element_)
            + toString(this._dot_)
            + toString(this._part_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._element_ == child)
        {
            this._element_ = null;
            return;
        }

        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        if(this._part_ == child)
        {
            this._part_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._element_ == oldChild)
        {
            setElement((TIdentifier) newChild);
            return;
        }

        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(this._part_ == oldChild)
        {
            setPart((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
