/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import java.util.*;
import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class ATree extends PTree
{
    private TTreeKeyword _treeKeyword_;
    private final LinkedList<PTreeProduction> _treeProductions_ = new LinkedList<PTreeProduction>();

    public ATree()
    {
        // Constructor
    }

    public ATree(
        @SuppressWarnings("hiding") TTreeKeyword _treeKeyword_,
        @SuppressWarnings("hiding") List<PTreeProduction> _treeProductions_)
    {
        // Constructor
        setTreeKeyword(_treeKeyword_);

        setTreeProductions(_treeProductions_);

    }

    @Override
    public Object clone()
    {
        return new ATree(
            cloneNode(this._treeKeyword_),
            cloneList(this._treeProductions_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATree(this);
    }

    public TTreeKeyword getTreeKeyword()
    {
        return this._treeKeyword_;
    }

    public void setTreeKeyword(TTreeKeyword node)
    {
        if(this._treeKeyword_ != null)
        {
            this._treeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._treeKeyword_ = node;
    }

    public LinkedList<PTreeProduction> getTreeProductions()
    {
        return this._treeProductions_;
    }

    public void setTreeProductions(List<PTreeProduction> list)
    {
        this._treeProductions_.clear();
        this._treeProductions_.addAll(list);
        for(PTreeProduction e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._treeKeyword_)
            + toString(this._treeProductions_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._treeKeyword_ == child)
        {
            this._treeKeyword_ = null;
            return;
        }

        if(this._treeProductions_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._treeKeyword_ == oldChild)
        {
            setTreeKeyword((TTreeKeyword) newChild);
            return;
        }

        for(ListIterator<PTreeProduction> i = this._treeProductions_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTreeProduction) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
