/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import java.util.*;
import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class ATreeProduction extends PTreeProduction
{
    private TIdentifier _name_;
    private TAssign _assign_;
    private final LinkedList<PTreeAlternative> _treeAlternatives_ = new LinkedList<PTreeAlternative>();

    public ATreeProduction()
    {
        // Constructor
    }

    public ATreeProduction(
        @SuppressWarnings("hiding") TIdentifier _name_,
        @SuppressWarnings("hiding") TAssign _assign_,
        @SuppressWarnings("hiding") List<PTreeAlternative> _treeAlternatives_)
    {
        // Constructor
        setName(_name_);

        setAssign(_assign_);

        setTreeAlternatives(_treeAlternatives_);

    }

    @Override
    public Object clone()
    {
        return new ATreeProduction(
            cloneNode(this._name_),
            cloneNode(this._assign_),
            cloneList(this._treeAlternatives_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATreeProduction(this);
    }

    public TIdentifier getName()
    {
        return this._name_;
    }

    public void setName(TIdentifier node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TAssign getAssign()
    {
        return this._assign_;
    }

    public void setAssign(TAssign node)
    {
        if(this._assign_ != null)
        {
            this._assign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assign_ = node;
    }

    public LinkedList<PTreeAlternative> getTreeAlternatives()
    {
        return this._treeAlternatives_;
    }

    public void setTreeAlternatives(List<PTreeAlternative> list)
    {
        this._treeAlternatives_.clear();
        this._treeAlternatives_.addAll(list);
        for(PTreeAlternative e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._assign_)
            + toString(this._treeAlternatives_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._assign_ == child)
        {
            this._assign_ = null;
            return;
        }

        if(this._treeAlternatives_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TIdentifier) newChild);
            return;
        }

        if(this._assign_ == oldChild)
        {
            setAssign((TAssign) newChild);
            return;
        }

        for(ListIterator<PTreeAlternative> i = this._treeAlternatives_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTreeAlternative) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
