/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AUnnamedAlternativeReference extends PAlternativeReference
{
    private TIdentifier _production_;

    public AUnnamedAlternativeReference()
    {
        // Constructor
    }

    public AUnnamedAlternativeReference(
        @SuppressWarnings("hiding") TIdentifier _production_)
    {
        // Constructor
        setProduction(_production_);

    }

    @Override
    public Object clone()
    {
        return new AUnnamedAlternativeReference(
            cloneNode(this._production_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnnamedAlternativeReference(this);
    }

    public TIdentifier getProduction()
    {
        return this._production_;
    }

    public void setProduction(TIdentifier node)
    {
        if(this._production_ != null)
        {
            this._production_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._production_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._production_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._production_ == child)
        {
            this._production_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._production_ == oldChild)
        {
            setProduction((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
