/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TIgnoredKeyword extends Token
{
    public TIgnoredKeyword()
    {
        super.setText("Ignored");
    }

    public TIgnoredKeyword(int line, int pos)
    {
        super.setText("Ignored");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIgnoredKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIgnoredKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIgnoredKeyword text.");
    }
}
