/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TNewKeyword extends Token
{
    public TNewKeyword()
    {
        super.setText("New");
    }

    public TNewKeyword(int line, int pos)
    {
        super.setText("New");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNewKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNewKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNewKeyword text.");
    }
}
