/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TPriorityKeyword extends Token
{
    public TPriorityKeyword()
    {
        super.setText("Priority");
    }

    public TPriorityKeyword(int line, int pos)
    {
        super.setText("Priority");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPriorityKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPriorityKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPriorityKeyword text.");
    }
}
