/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TProductionKeyword extends Token
{
    public TProductionKeyword()
    {
        super.setText("Production");
    }

    public TProductionKeyword(int line, int pos)
    {
        super.setText("Production");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TProductionKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProductionKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TProductionKeyword text.");
    }
}
