/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TRightKeyword extends Token
{
    public TRightKeyword()
    {
        super.setText("Right");
    }

    public TRightKeyword(int line, int pos)
    {
        super.setText("Right");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRightKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRightKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRightKeyword text.");
    }
}
