/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TTreeKeyword extends Token
{
    public TTreeKeyword()
    {
        super.setText("Tree");
    }

    public TTreeKeyword(int line, int pos)
    {
        super.setText("Tree");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTreeKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTreeKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTreeKeyword text.");
    }
}
