/* Generated by build.xml */

package org.sablecc.objectmacro.launcher;

import org.sablecc.exception.InternalException;

/**
 * This class provides the version.
 */
public class Version {

    /** The version. */
    public static final String VERSION = "4-beta.2";

    /** Prevents instantiation of this class. */
    private Version() {

        throw new InternalException("no instance allowed");
    }
}
