/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

class N$20
    extends Token {

  N$20(String text, int line, int pos) {
    super(text, line, pos);
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_$20;
  }
}
