/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

public class NCloses_Ifelse
    extends NCloses {

  private final int line;
  private final int pos;
  private final N$6 e$6;
  private final NC eC;
  private final NCloses eCloses$1;
  private final N$7 e$7;
  private final NCloses eCloses$2;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inCloses_Ifelse(this);
    walker.caseCloses_Ifelse(this);
    walker.outCloses_Ifelse(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$6.apply(walker);
    this.eC.apply(walker);
    this.eCloses$1.apply(walker);
    this.e$7.apply(walker);
    this.eCloses$2.apply(walker);
  }

  NCloses_Ifelse(int line, int pos, N$6 p$6, NC pC, NCloses pCloses$1, N$7 p$7, NCloses pCloses$2) {
    this.line = line;
    this.pos = pos;
    this.e$6 = p$6;
    this.eC = pC;
    this.eCloses$1 = pCloses$1;
    this.e$7 = p$7;
    this.eCloses$2 = pCloses$2;
  }

  @Override
  public Type getType() {
    return Type.T_Closes_Ifelse;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Closes;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Closes_Ifelse;
  }

  public NC get_C() {
    return this.eC;
  }

  N$6 internalGet$6() {
    return this.e$6;
  }

  NC internalGetC() {
    return this.eC;
  }

  NCloses internalGetCloses$1() {
    return this.eCloses$1;
  }

  N$7 internalGet$7() {
    return this.e$7;
  }

  NCloses internalGetCloses$2() {
    return this.eCloses$2;
  }
}
