/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

public class NCloses_Stmts
    extends NCloses {

  private final int line;
  private final int pos;
  private final N$4 e$4;
  private final NStmts eStmts;
  private final N$5 e$5;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inCloses_Stmts(this);
    walker.caseCloses_Stmts(this);
    walker.outCloses_Stmts(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$4.apply(walker);
    this.eStmts.apply(walker);
    this.e$5.apply(walker);
  }

  NCloses_Stmts(int line, int pos, N$4 p$4, NStmts pStmts, N$5 p$5) {
    this.line = line;
    this.pos = pos;
    this.e$4 = p$4;
    this.eStmts = pStmts;
    this.e$5 = p$5;
  }

  @Override
  public Type getType() {
    return Type.T_Closes_Stmts;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Closes;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Closes_Stmts;
  }

  public NStmts get_Stmts() {
    return this.eStmts;
  }

  N$4 internalGet$4() {
    return this.e$4;
  }

  NStmts internalGetStmts() {
    return this.eStmts;
  }

  N$5 internalGet$5() {
    return this.e$5;
  }
}
