/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

public class NCp_Le
    extends NCp {

  private final int line;
  private final int pos;
  private final N$19 e$19;
  private final NE eRight;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inCp_Le(this);
    walker.caseCp_Le(this);
    walker.outCp_Le(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$19.apply(walker);
    this.eRight.apply(walker);
  }

  NCp_Le(int line, int pos, N$19 p$19, NE pRight) {
    this.line = line;
    this.pos = pos;
    this.e$19 = p$19;
    this.eRight = pRight;
  }

  @Override
  public Type getType() {
    return Type.T_Cp_Le;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Cp;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Cp_Le;
  }

  public NE get_Right() {
    return this.eRight;
  }

  N$19 internalGet$19() {
    return this.e$19;
  }

  NE internalGetRight() {
    return this.eRight;
  }
}
