/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

public class NCp_Gt
    extends NCp {

  private final int line;
  private final int pos;
  private final N$20 e$20;
  private final NE eRight;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inCp_Gt(this);
    walker.caseCp_Gt(this);
    walker.outCp_Gt(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$20.apply(walker);
    this.eRight.apply(walker);
  }

  NCp_Gt(int line, int pos, N$20 p$20, NE pRight) {
    this.line = line;
    this.pos = pos;
    this.e$20 = p$20;
    this.eRight = pRight;
  }

  @Override
  public Type getType() {
    return Type.T_Cp_Gt;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Cp;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Cp_Gt;
  }

  public NE get_Right() {
    return this.eRight;
  }

  N$20 internalGet$20() {
    return this.e$20;
  }

  NE internalGetRight() {
    return this.eRight;
  }
}
