/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

public class NEa_Sub
    extends NEa {

  private final int line;
  private final int pos;
  private final NE eE;
  private final N$9 e$9;
  private final NEa eEa;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inEa_Sub(this);
    walker.caseEa_Sub(this);
    walker.outEa_Sub(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eE.apply(walker);
    this.e$9.apply(walker);
    this.eEa.apply(walker);
  }

  NEa_Sub(int line, int pos, NE pE, N$9 p$9, NEa pEa) {
    this.line = line;
    this.pos = pos;
    this.eE = pE;
    this.e$9 = p$9;
    this.eEa = pEa;
  }

  @Override
  public Type getType() {
    return Type.T_Ea_Sub;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Ea;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Ea_Sub;
  }

  public NE get_E() {
    return this.eE;
  }

  public NEa get_Ea() {
    return this.eEa;
  }

  NE internalGetE() {
    return this.eE;
  }

  N$9 internalGet$9() {
    return this.e$9;
  }

  NEa internalGetEa() {
    return this.eEa;
  }
}
