/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

public class NEm_Div
    extends NEm {

  private final int line;
  private final int pos;
  private final NE eE;
  private final N$11 e$11;
  private final NEm eEm;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inEm_Div(this);
    walker.caseEm_Div(this);
    walker.outEm_Div(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eE.apply(walker);
    this.e$11.apply(walker);
    this.eEm.apply(walker);
  }

  NEm_Div(int line, int pos, NE pE, N$11 p$11, NEm pEm) {
    this.line = line;
    this.pos = pos;
    this.eE = pE;
    this.e$11 = p$11;
    this.eEm = pEm;
  }

  @Override
  public Type getType() {
    return Type.T_Em_Div;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Em;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Em_Div;
  }

  public NE get_E() {
    return this.eE;
  }

  public NEm get_Em() {
    return this.eEm;
  }

  NE internalGetE() {
    return this.eE;
  }

  N$11 internalGet$11() {
    return this.e$11;
  }

  NEm internalGetEm() {
    return this.eEm;
  }
}
