/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

public class NEm_Mul
    extends NEm {

  private final int line;
  private final int pos;
  private final NE eE;
  private final N$10 e$10;
  private final NEm eEm;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inEm_Mul(this);
    walker.caseEm_Mul(this);
    walker.outEm_Mul(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eE.apply(walker);
    this.e$10.apply(walker);
    this.eEm.apply(walker);
  }

  NEm_Mul(int line, int pos, NE pE, N$10 p$10, NEm pEm) {
    this.line = line;
    this.pos = pos;
    this.eE = pE;
    this.e$10 = p$10;
    this.eEm = pEm;
  }

  @Override
  public Type getType() {
    return Type.T_Em_Mul;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Em;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Em_Mul;
  }

  public NE get_E() {
    return this.eE;
  }

  public NEm get_Em() {
    return this.eEm;
  }

  NE internalGetE() {
    return this.eE;
  }

  N$10 internalGet$10() {
    return this.e$10;
  }

  NEm internalGetEm() {
    return this.eEm;
  }
}
