/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

public class NExpr_Str
    extends NExpr {

  private final int line;
  private final int pos;
  private final NStr eStr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inExpr_Str(this);
    walker.caseExpr_Str(this);
    walker.outExpr_Str(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eStr.apply(walker);
  }

  public NExpr_Str(int line, int pos, NStr pStr) {
    this.line = line;
    this.pos = pos;
    this.eStr = pStr;
  }

  @Override
  public Type getType() {
    return Type.T_Expr_Str;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Expr;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Expr_Str;
  }

  public NStr get_Str() {
    return this.eStr;
  }

  NStr internalGetStr() {
    return this.eStr;
  }
}
