/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

class NProg_$1
    extends NProg {

  private final int line;
  private final int pos;
  private final NStmt eStmt;
  private final NProg eProg;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eStmt.apply(walker);
    this.eProg.apply(walker);
  }

  NProg_$1(int line, int pos, NStmt pStmt, NProg pProg) {
    this.line = line;
    this.pos = pos;
    this.eStmt = pStmt;
    this.eProg = pProg;
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Prog;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Prog_$1;
  }

  NStmt internalGetStmt() {
    return this.eStmt;
  }

  NProg internalGetProg() {
    return this.eProg;
  }
}
