/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

class S_0
    extends TransitionState {

  static final S_0 instance = new S_0();

  private S_0() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol_9:
      return S_1.instance;
    case Symbol_10:
      return S_1.instance;
    case Symbol_34:
      return S_2.instance;
    case Symbol_40:
      return S_3.instance;
    case Symbol_41:
      return S_4.instance;
    case Symbol_47:
      return S_5.instance;
    case Symbol__0:
      return S_6.instance;
    case Symbol__p:
      return S_7.instance;
    default:
      return null;
    }
  }

}
