/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

class S_13
    extends TransitionState {

  static final S_13 instance = new S_13();

  private S_13() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__n:
      return S_14.instance;
    default:
      return null;
    }
  }

}
