/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

class S_26
    extends FinalState {

  static final S_26 instance = new S_26();

  private S_26() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new NStr(text, line, pos);
  }
}
