/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

class S_3
    extends FinalState {

  static final S_3 instance = new S_3();

  private S_3() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$1(text, line, pos);
  }
}
