/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

class S_5
    extends TransitionState {

  static final S_5 instance = new S_5();

  private S_5() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol_47:
      return S_9.instance;
    default:
      return null;
    }
  }

}
