/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

class S_59
    extends FinalState {

  static final S_59 instance = new S_59();

  private S_59() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$2(text, line, pos);
  }
}
