/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

class S_6
    extends TransitionState {

  static final S_6 instance = new S_6();

  private S_6() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol_min:
      return S_10.instance;
    case Symbol_9:
      return S_10.instance;
    case Symbol_10:
      return S_10.instance;
    case Symbol_34:
      return S_10.instance;
    case Symbol_40:
      return S_10.instance;
    case Symbol_41:
      return S_10.instance;
    case Symbol_47:
      return S_10.instance;
    case Symbol__0:
      return S_6.instance;
    case Symbol__i:
      return S_10.instance;
    case Symbol__n:
      return S_10.instance;
    case Symbol__p:
      return S_10.instance;
    case Symbol__r:
      return S_10.instance;
    case Symbol__t:
      return S_10.instance;
    case Symbol_end:
      return S_10.instance;
    default:
      return null;
    }
  }

}
