/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

class S_62
    extends FinalState {

  static final S_62 instance = new S_62();

  private S_62() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$13(text, line, pos);
  }
}
