/* This file was generated by SableCC ( http://sablecc.org ). */

package language_minilang;

enum Symbol {
  Symbol_min,
  Symbol_9,
  Symbol_10,
  Symbol_34,
  Symbol_40,
  Symbol_41,
  Symbol_47,
  Symbol__0,
  Symbol__i,
  Symbol__n,
  Symbol__p,
  Symbol__r,
  Symbol__t,
  Symbol_end;

  static Symbol getSymbol(char c) {
    switch(c) {
    case 9: return Symbol_9;
    case 10: return Symbol_10;
    case 32: return Symbol_9;
    case 33: return Symbol_min;
    case 34: return Symbol_34;
    case 40: return Symbol_40;
    case 41: return Symbol_41;
    case 47: return Symbol_47;
    case 105: return Symbol__i;
    case 110: return Symbol__n;
    case 111: return Symbol_min;
    case 112: return Symbol__p;
    case 113: return Symbol_min;
    case 114: return Symbol__r;
    case 115: return Symbol_min;
    case 116: return Symbol__t;
    default:
      if(c <= 8) {
        return Symbol_min;
      }
      if(c >= 117) {
        return Symbol_min;
      }
      if(c >= 11 && c <= 31) {
        return Symbol_min;
      }
      if(c >= 35 && c <= 39) {
        return Symbol_min;
      }
      if(c >= 42 && c <= 46) {
        return Symbol_min;
      }
      if(c >= 48 && c <= 57) {
        return Symbol__0;
      }
      if(c >= 58 && c <= 104) {
        return Symbol_min;
      }
      if(c >= 106 && c <= 109) {
        return Symbol_min;
      }
    }

    return null;
  }
}
