/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.objectmacro.syntax3.node;

import org.sablecc.objectmacro.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AEscapeStringPart extends PStringPart
{
    private TStringEscape _escape_;

    public AEscapeStringPart()
    {
        // Constructor
    }

    public AEscapeStringPart(
        @SuppressWarnings("hiding") TStringEscape _escape_)
    {
        // Constructor
        setEscape(_escape_);

    }

    @Override
    public Object clone()
    {
        return new AEscapeStringPart(
            cloneNode(this._escape_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEscapeStringPart(this);
    }

    public TStringEscape getEscape()
    {
        return this._escape_;
    }

    public void setEscape(TStringEscape node)
    {
        if(this._escape_ != null)
        {
            this._escape_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escape_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escape_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escape_ == child)
        {
            this._escape_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escape_ == oldChild)
        {
            setEscape((TStringEscape) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
