/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.objectmacro.syntax3.node;

import org.sablecc.objectmacro.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AExpandMacroBodyPart extends PMacroBodyPart
{
    private PExpand _expand_;

    public AExpandMacroBodyPart()
    {
        // Constructor
    }

    public AExpandMacroBodyPart(
        @SuppressWarnings("hiding") PExpand _expand_)
    {
        // Constructor
        setExpand(_expand_);

    }

    @Override
    public Object clone()
    {
        return new AExpandMacroBodyPart(
            cloneNode(this._expand_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpandMacroBodyPart(this);
    }

    public PExpand getExpand()
    {
        return this._expand_;
    }

    public void setExpand(PExpand node)
    {
        if(this._expand_ != null)
        {
            this._expand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expand_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expand_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expand_ == child)
        {
            this._expand_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expand_ == oldChild)
        {
            setExpand((PExpand) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
