/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.objectmacro.syntax3.node;

import org.sablecc.objectmacro.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TExpandCommand extends Token
{
    public TExpandCommand()
    {
        super.setText("$expand:");
    }

    public TExpandCommand(int line, int pos)
    {
        super.setText("$expand:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TExpandCommand(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTExpandCommand(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TExpandCommand text.");
    }
}
