/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.objectmacro.syntax3.node;

import org.sablecc.objectmacro.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TInvalidMidLineNoEol extends Token
{
    public TInvalidMidLineNoEol()
    {
        super.setText("$no_eol$");
    }

    public TInvalidMidLineNoEol(int line, int pos)
    {
        super.setText("$no_eol$");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInvalidMidLineNoEol(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInvalidMidLineNoEol(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInvalidMidLineNoEol text.");
    }
}
