/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.objectmacro.syntax3.node;

import org.sablecc.objectmacro.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TTextBlockCommand extends Token
{
    public TTextBlockCommand()
    {
        super.setText("$text:");
    }

    public TTextBlockCommand(int line, int pos)
    {
        super.setText("$text:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTextBlockCommand(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTextBlockCommand(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTextBlockCommand text.");
    }
}
